// SPDX-License-Identifier: MIT

import { describe, expect, it } from "vitest";
import { renderHostHeaders, suggestCacheControl, type StaticExportManifest } from "../manifest.js";

const cache = {
  enabled: true,
  htmlMaxAge: 120,
  staticMaxAge: 86_400,
  staleWhileRevalidate: 600,
};

describe("static export cache headers", () => {
  it("uses the active browser-cache settings", () => {
    expect(suggestCacheControl("/about", "text/html", cache)).toBe(
      "public, max-age=120, stale-while-revalidate=600",
    );
    // Unversioned asset: keep the URL across re-exports, so it must stay
    // revalidatable — never `immutable`.
    expect(suggestCacheControl("/theme.css", "text/css", cache)).toBe(
      "public, max-age=86400, stale-while-revalidate=600",
    );
    // A content-hashed filename is safe to freeze.
    expect(suggestCacheControl("/assets/app.9f8e7d6c.js", "text/javascript", cache)).toBe(
      "public, max-age=86400, immutable",
    );
    expect(suggestCacheControl("/robots.txt", "text/plain", cache)).toBe("public, max-age=120");
  });

  it("prevents host caching when browser caching is disabled", () => {
    expect(suggestCacheControl("/", "text/html", { ...cache, enabled: false })).toBe("no-store");
  });

  it("writes deployable rules for routes and assets", () => {
    const manifest = {
      generatedAt: "2026-09-03T00:00:00.000Z",
      mode: "full",
      justflowsVersion: "0.1.5",
      publicUrl: "https://example.com",
      routes: [{ path: "/", cacheControl: "public, max-age=120" }],
      assets: [
        { path: "/assets/app.9f8e7d6c.js", cacheControl: "public, max-age=86400, immutable" },
      ],
      config: { maxPages: 10, concurrency: 1 },
    } as StaticExportManifest;

    expect(renderHostHeaders(manifest)).toBe(
      "# Generated by Justflows static export. Do not edit.\n" +
        "/*\n  X-Powered-By: Justflows\n" +
        "/\n  Cache-Control: public, max-age=120\n" +
        "/assets/app.9f8e7d6c.js\n  Cache-Control: public, max-age=86400, immutable\n",
    );
  });
});
