// SPDX-License-Identifier: MIT

import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { MANIFEST_FILE } from "./config.js";

/** Coarse record of what a rendered route depended on, used for incremental rebuilds. */
export interface RouteDeps {
  /** Content ids whose HTML appears on this route (single pages, list items). */
  content: string[];
  /** Translation-group ids, so publishing any locale variant invalidates siblings. */
  translationGroups: string[];
  /** Locale this route was rendered for. */
  locale?: string;
  /** True when the route embeds a dynamic listing (blog list, search) and should
   *  be rebuilt on any content change, not only its own ids. */
  dynamicList: boolean;
}

export interface ManifestRoute {
  /** Normalized URL path (`/`, `/about`, `/nl-NL/over-ons`). */
  path: string;
  /** Output file relative to the export directory. */
  file: string;
  status: number;
  contentType: string;
  bytes: number;
  sha256: string;
  deps: RouteDeps;
  /** Suggested `Cache-Control` for a CDN/object-store upload of this file. */
  cacheControl: string;
}

export interface ManifestAsset {
  path: string;
  file: string;
  status: number;
  contentType: string;
  bytes: number;
  sha256: string;
  cacheControl: string;
}

export interface StaticExportManifest {
  generatedAt: string;
  /** "full" or "incremental" — the run that last touched the manifest. */
  mode: "full" | "incremental";
  justflowsVersion: string;
  /** Public origin the pages are meant to be served from (may be ""). */
  publicUrl: string;
  routes: ManifestRoute[];
  assets: ManifestAsset[];
  config: {
    maxPages: number;
    concurrency: number;
  };
}

export interface StaticExportBrowserCacheConfig {
  enabled: boolean;
  htmlMaxAge: number;
  staticMaxAge: number;
  staleWhileRevalidate: number;
}

/** Cloudflare Pages / Netlify header rules generated beside the export. */
export const HOST_HEADERS_FILE = "_headers";

export function sha256(body: Buffer | string): string {
  return createHash("sha256").update(body).digest("hex");
}

/** A path that carries its own content hash (`app.9f8e7d6c.js`) — safe to freeze. */
const FINGERPRINTED_RE = /[.-][0-9a-f]{8,}\.[a-z0-9]+$/i;

/**
 * `Cache-Control` advice for a CDN/object-store sync. HTML is revalidated often
 * (content changes); only fingerprinted assets get `immutable` — an unversioned
 * `/theme.css` or `/uploads/logo.png` keeps its URL across re-exports, so it
 * must stay revalidatable or a changed file is never picked up.
 */
export function suggestCacheControl(
  urlPath: string,
  contentType: string,
  browserCache?: StaticExportBrowserCacheConfig,
): string {
  if (browserCache && !browserCache.enabled) return "no-store";
  if (browserCache) {
    if (/\/(sitemap\.xml|robots\.txt)$/i.test(urlPath)) {
      return `public, max-age=${browserCache.htmlMaxAge}`;
    }
    if (contentType.includes("text/html")) {
      return (
        `public, max-age=${browserCache.htmlMaxAge}, ` +
        `stale-while-revalidate=${browserCache.staleWhileRevalidate}`
      );
    }
    return FINGERPRINTED_RE.test(urlPath)
      ? `public, max-age=${browserCache.staticMaxAge}, immutable`
      : `public, max-age=${browserCache.staticMaxAge}, ` +
          `stale-while-revalidate=${browserCache.staleWhileRevalidate}`;
  }
  if (contentType.includes("text/html")) return "public, max-age=60, s-maxage=300";
  if (/\/(sitemap\.xml|robots\.txt)$/i.test(urlPath)) return "public, max-age=300, s-maxage=600";
  if (FINGERPRINTED_RE.test(urlPath)) {
    return "public, max-age=31536000, immutable";
  }
  return "public, max-age=3600, s-maxage=86400";
}

/** Render the `_headers` format understood by Cloudflare Pages and Netlify. */
export function renderHostHeaders(manifest: StaticExportManifest): string {
  const rules = new Map<string, string>();
  for (const entry of [...manifest.routes, ...manifest.assets]) {
    rules.set(entry.path, entry.cacheControl);
  }
  const lines = [
    "# Generated by Justflows static export. Do not edit.",
    "/*",
    "  X-Powered-By: Justflows",
  ];
  for (const [urlPath, cacheControl] of [...rules].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(urlPath, `  Cache-Control: ${cacheControl}`);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Web-server config generated beside the export, the counterpart to `_headers`
 * for Cloudflare Pages / Netlify. `.htaccess` is read automatically by Apache
 * when the vhost allows overrides; `_nginx.conf` is `include`d from an nginx
 * `server {}` block. Both are inert on object storage. WordPress ships the same
 * pair — see the "web server" pages in its advanced-administration docs.
 */
export const HTACCESS_FILE = ".htaccess";
export const NGINX_FILE = "_nginx.conf";

export { MANAGED_SENTINEL, writeManagedFile } from "../managed-config.js";

/** First line of the static-export config files (starts with `MANAGED_SENTINEL`). */
const STATIC_EXPORT_SENTINEL = "# Generated by Justflows static export.";

/**
 * The dynamic prefixes that must reach the app, not the exported files (union of
 * `crawl.ts` reserved prefixes and `assets.ts` deny prefixes). `admin` is the
 * configured admin path, passed in because it is a runtime setting.
 */
const DYNAMIC_PREFIXES = [
  "api",
  "login",
  "register",
  "install",
  "forgot-password",
  "reset-password",
  "set-locale",
  "justflows-forms",
  "justflows-comments",
  "justflows-analytics",
];

/** Regex-alternation of the dynamic prefixes with the live admin path first. */
function dynamicPrefixGroup(adminPath: string): string {
  const adminToken = adminPath.replace(/^\/+/, "").replace(/\/+$/, "");
  return [adminToken, ...DYNAMIC_PREFIXES]
    .map((p) => p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("|");
}

/**
 * Render the managed `.htaccess`. The serving rules (directory index,
 * extensionless-route rewrite, themed 404) plus WordPress-style hardening are
 * emitted live; the route to the dynamic app is host-specific, so it ships
 * commented out.
 */
export function renderHtaccess(opts: { adminPath: string }): string {
  const group = dynamicPrefixGroup(opts.adminPath);
  return `${STATIC_EXPORT_SENTINEL}
# Managed block — regenerated on every export while the line above is intact.
# Change/remove that line, or delete the file, to keep hand edits. The route to
# the dynamic app (admin, API, form/comment POST) is host-specific and lives in
# the vhost, not here — see docs/STATIC-EXPORT.md. This file serves the
# published static site and hardens it.

# ---------------------------------------------------------------------------
# Serving
# ---------------------------------------------------------------------------
DirectoryIndex index.html
ErrorDocument 404 /404.html
# Remove the next line if Apache reports "Options not allowed here" (the vhost's
# AllowOverride does not grant Options) — directory listing is usually off anyway.
Options -Indexes

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Extensionless published route -> its index.html when that file exists,
  # so /contact serves contact/index.html without a trailing slash.
  RewriteCond %{DOCUMENT_ROOT}/$1/index.html -f
  RewriteRule ^(.+?)/?$ /$1/index.html [L]

  # Dynamic surface -> the Justflows app. How you route it depends on how the
  # app runs on this host:
  #   * A module that already serves non-file requests (e.g. Phusion Passenger):
  #     no rule needed here — just set its DocumentRoot to this directory.
  #   * Reverse proxy to a Node process: enable mod_proxy, set the address, and
  #     uncomment the next line (then remove the sentinel line at the top so this
  #     file stops being regenerated):
  # RewriteRule ^(${group})(/|$) http://127.0.0.1:3000%{REQUEST_URI} [P,L]
</IfModule>

# ---------------------------------------------------------------------------
# Hardening
# ---------------------------------------------------------------------------

# Dotfiles (.git, .env, …) and Justflows/server metadata are never downloadable.
# /.well-known/ (ACME, security.txt) is a directory, so its files are unaffected.
<FilesMatch "^\\.|^_(headers|nginx\\.conf|static-export\\.json|redirects)$|\\.(bak|config|dist|fla|inc|ini|log|orig|psd|save|sh|sql|swp|swo|tmp)$|~$">
  Require all denied
</FilesMatch>

# No server-side script execution anywhere in the export (defence in depth —
# these are plain files; nothing here should ever run).
<FilesMatch "\\.(php[0-9]?|phtml|phar|pl|py|cgi|lua|rb|asp|aspx|jsp)$">
  Require all denied
</FilesMatch>
<IfModule mod_mime.c>
  RemoveHandler .php .phtml .phar .pl .py .cgi .lua .rb
  RemoveType .php .phtml .phar
</IfModule>

<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  Header always set X-Frame-Options "SAMEORIGIN"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set Cross-Origin-Opener-Policy "same-origin"
  Header always set X-Powered-By "Justflows"
  Header always unset X-Pingback
  # HTTPS only — uncomment once every hostname for this site serves HTTPS:
  # Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
</IfModule>

# ---------------------------------------------------------------------------
# Caching & compression
# ---------------------------------------------------------------------------
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml application/javascript application/json application/xml image/svg+xml application/rss+xml application/atom+xml font/ttf font/otf application/vnd.ms-fontobject
</IfModule>
<IfModule mod_headers.c>
  # Fingerprinted assets (name carries a content hash) never change — freeze.
  <FilesMatch "[._-][0-9a-f]{8,}\\.(js|css|woff2?|png|jpe?g|gif|svg|webp|avif|ico)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
</IfModule>
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css                   "access plus 1 day"
  ExpiresByType application/javascript     "access plus 1 day"
  ExpiresByType image/svg+xml              "access plus 7 days"
  ExpiresByType image/png                  "access plus 7 days"
  ExpiresByType image/jpeg                 "access plus 7 days"
  ExpiresByType image/webp                 "access plus 7 days"
  ExpiresByType image/avif                 "access plus 7 days"
  ExpiresByType font/woff2                 "access plus 30 days"
  ExpiresByType text/html                  "access plus 0 seconds"
</IfModule>
`;
}

/**
 * Render the managed `_nginx.conf` — an `include` for an nginx `server {}`
 * block. `root` is pinned to this run's output directory (WordPress does the
 * same). The vhost supplies `@fallback`: whatever routes to the Justflows app
 * on this host — a reverse proxy, Phusion Passenger, a unix socket, anything.
 */
export function renderNginxConf(opts: { adminPath: string; rootDir: string }): string {
  const adminLoc = opts.adminPath.replace(/\/+$/, "");
  return `${STATIC_EXPORT_SENTINEL}
# Managed block — regenerated on every export while the line above is intact.
# Change/remove that line, or delete the file, to keep hand edits.
#
# Include it from your server {} block:
#     include ${opts.rootDir}/_nginx.conf;
# and define @fallback (whatever routes to the Justflows app on this host) in
# the vhost — see the bottom of this file and docs/STATIC-EXPORT.md.

root "${opts.rootDir}";
index index.html;
autoindex off;
error_page 404 /404.html;

# --- security headers (no location below sets add_header, so these inherit) ---
add_header X-Content-Type-Options   "nosniff" always;
add_header X-Frame-Options          "SAMEORIGIN" always;
add_header Referrer-Policy          "strict-origin-when-cross-origin" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header X-Powered-By             "Justflows" always;
# HTTPS only — uncomment once every hostname for this site serves HTTPS:
# add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# --- dynamic app: never served from the static export ---
location ^~ ${adminLoc}  { try_files /_pass @fallback; }
location ^~ /api/                { try_files /_pass @fallback; }
location ^~ /login               { try_files /_pass @fallback; }
location ^~ /register            { try_files /_pass @fallback; }
location ^~ /install             { try_files /_pass @fallback; }
location ^~ /forgot-password     { try_files /_pass @fallback; }
location ^~ /reset-password      { try_files /_pass @fallback; }
location ^~ /set-locale          { try_files /_pass @fallback; }
location ^~ /justflows-forms/        { try_files /_pass @fallback; }
location ^~ /justflows-comments/     { try_files /_pass @fallback; }
location ^~ /justflows-analytics/    { try_files /_pass @fallback; }
# plugin assets are exported, but consent record/cookies are dynamic
location ^~ /ext/                { try_files $uri @fallback; }

# --- hardening ---
# dotfiles (.git, .env, …) — keep /.well-known/ reachable
location ~ /\\.(?!well-known/) { deny all; }
# Justflows + server metadata must not be downloadable
location ~ ^/_(headers|nginx\\.conf|static-export\\.json|redirects)$ { deny all; }
# no script execution under uploads (defence in depth)
location ~* ^/uploads/.*\\.(php[0-9]?|phtml|phar|pl|py|cgi|lua|rb|asp|aspx|jsp)$ { deny all; }
# source / backup / dump extensions
location ~* \\.(bak|config|dist|fla|inc|ini|log|orig|psd|save|sh|sql|swp|swo|tmp)$ { deny all; }

# --- caching ---
location = /favicon.ico { log_not_found off; access_log off; }
location = /robots.txt  { log_not_found off; access_log off; }
location ~* [._-][0-9a-f]{8,}\\.(js|css|woff2?|png|jpe?g|gif|svg|webp|avif|ico)$ {
  expires max;
  access_log off;
}
location ~* \\.(js|css|woff2?|png|jpe?g|gif|svg|webp|avif|ico|map)$ {
  expires 1d;
  access_log off;
}

# --- published site: static export, app as fallback ---
location / {
  try_files $uri/index.html $uri @fallback;
}

# --- define @fallback in the vhost: whatever routes to the Justflows app ---
# reverse proxy to a Node process (TCP or unix socket):
#   location @fallback {
#     proxy_pass http://127.0.0.1:3000;   # or http://unix:/run/justflows.sock:
#     proxy_http_version 1.1;
#     proxy_set_header Host $host;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto $scheme;
#   }
# …or Phusion Passenger:
#   location @fallback {
#     passenger_enabled on;
#     passenger_app_root /path/to/justflows;
#     passenger_app_type node;
#     passenger_startup_file server.js;
#   }
`;
}

export function manifestPath(outDir: string): string {
  return path.join(outDir, MANIFEST_FILE);
}

export async function readManifest(outDir: string): Promise<StaticExportManifest | null> {
  try {
    const raw = await fs.readFile(manifestPath(outDir), "utf8");
    const parsed = JSON.parse(raw) as StaticExportManifest;
    if (!Array.isArray(parsed.routes) || !Array.isArray(parsed.assets)) return null;
    return parsed;
  } catch {
    return null;
  }
}

export async function writeManifest(outDir: string, manifest: StaticExportManifest): Promise<void> {
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(manifestPath(outDir), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

/** Every output file the manifest accounts for (routes + assets + the manifest itself). */
export function manifestFiles(manifest: StaticExportManifest | null): Set<string> {
  const files = new Set<string>([MANIFEST_FILE, HOST_HEADERS_FILE, HTACCESS_FILE, NGINX_FILE]);
  if (!manifest) return files;
  for (const route of manifest.routes) files.add(route.file);
  for (const asset of manifest.assets) files.add(asset.file);
  return files;
}
