// SPDX-License-Identifier: MIT

import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { MANIFEST_FILE } from "./config.js";

/** Coarse record of what a rendered route depended on, used for incremental rebuilds. */
export interface RouteDeps {
  /** Content ids whose HTML appears on this route (single pages, list items). */
  content: string[];
  /** Translation-group ids, so publishing any locale variant invalidates siblings. */
  translationGroups: string[];
  /** Locale this route was rendered for. */
  locale?: string;
  /** True when the route embeds a dynamic listing (blog list, search) and should
   *  be rebuilt on any content change, not only its own ids. */
  dynamicList: boolean;
}

export interface ManifestRoute {
  /** Normalized URL path (`/`, `/about`, `/nl-NL/over-ons`). */
  path: string;
  /** Output file relative to the export directory. */
  file: string;
  status: number;
  contentType: string;
  bytes: number;
  sha256: string;
  deps: RouteDeps;
  /** Suggested `Cache-Control` for a CDN/object-store upload of this file. */
  cacheControl: string;
}

export interface ManifestAsset {
  path: string;
  file: string;
  status: number;
  contentType: string;
  bytes: number;
  sha256: string;
  cacheControl: string;
}

export interface StaticExportManifest {
  generatedAt: string;
  /** "full" or "incremental" — the run that last touched the manifest. */
  mode: "full" | "incremental";
  justflowsVersion: string;
  /** Public origin the pages are meant to be served from (may be ""). */
  publicUrl: string;
  routes: ManifestRoute[];
  assets: ManifestAsset[];
  config: {
    maxPages: number;
    concurrency: number;
  };
}

export interface StaticExportBrowserCacheConfig {
  enabled: boolean;
  htmlMaxAge: number;
  staticMaxAge: number;
  staleWhileRevalidate: number;
}

/** Cloudflare Pages / Netlify header rules generated beside the export. */
export const HOST_HEADERS_FILE = "_headers";

export function sha256(body: Buffer | string): string {
  return createHash("sha256").update(body).digest("hex");
}

/** A path that carries its own content hash (`app.9f8e7d6c.js`) — safe to freeze. */
const FINGERPRINTED_RE = /[.-][0-9a-f]{8,}\.[a-z0-9]+$/i;

/**
 * `Cache-Control` advice for a CDN/object-store sync. HTML is revalidated often
 * (content changes); only fingerprinted assets get `immutable` — an unversioned
 * `/theme.css` or `/uploads/logo.png` keeps its URL across re-exports, so it
 * must stay revalidatable or a changed file is never picked up.
 */
export function suggestCacheControl(
  urlPath: string,
  contentType: string,
  browserCache?: StaticExportBrowserCacheConfig,
): string {
  if (browserCache && !browserCache.enabled) return "no-store";
  if (browserCache) {
    if (/\/(sitemap\.xml|robots\.txt)$/i.test(urlPath)) {
      return `public, max-age=${browserCache.htmlMaxAge}`;
    }
    if (contentType.includes("text/html")) {
      return (
        `public, max-age=${browserCache.htmlMaxAge}, ` +
        `stale-while-revalidate=${browserCache.staleWhileRevalidate}`
      );
    }
    return FINGERPRINTED_RE.test(urlPath)
      ? `public, max-age=${browserCache.staticMaxAge}, immutable`
      : `public, max-age=${browserCache.staticMaxAge}, ` +
          `stale-while-revalidate=${browserCache.staleWhileRevalidate}`;
  }
  if (contentType.includes("text/html")) return "public, max-age=60, s-maxage=300";
  if (/\/(sitemap\.xml|robots\.txt)$/i.test(urlPath)) return "public, max-age=300, s-maxage=600";
  if (FINGERPRINTED_RE.test(urlPath)) {
    return "public, max-age=31536000, immutable";
  }
  return "public, max-age=3600, s-maxage=86400";
}

/** Render the `_headers` format understood by Cloudflare Pages and Netlify. */
export function renderHostHeaders(manifest: StaticExportManifest): string {
  const rules = new Map<string, string>();
  for (const entry of [...manifest.routes, ...manifest.assets]) {
    rules.set(entry.path, entry.cacheControl);
  }
  const lines = [
    "# Generated by Justflows static export. Do not edit.",
    "/*",
    "  X-Powered-By: Justflows",
  ];
  for (const [urlPath, cacheControl] of [...rules].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(urlPath, `  Cache-Control: ${cacheControl}`);
  }
  return `${lines.join("\n")}\n`;
}

export function manifestPath(outDir: string): string {
  return path.join(outDir, MANIFEST_FILE);
}

export async function readManifest(outDir: string): Promise<StaticExportManifest | null> {
  try {
    const raw = await fs.readFile(manifestPath(outDir), "utf8");
    const parsed = JSON.parse(raw) as StaticExportManifest;
    if (!Array.isArray(parsed.routes) || !Array.isArray(parsed.assets)) return null;
    return parsed;
  } catch {
    return null;
  }
}

export async function writeManifest(outDir: string, manifest: StaticExportManifest): Promise<void> {
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(manifestPath(outDir), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

/** Every output file the manifest accounts for (routes + assets + the manifest itself). */
export function manifestFiles(manifest: StaticExportManifest | null): Set<string> {
  const files = new Set<string>([MANIFEST_FILE, HOST_HEADERS_FILE]);
  if (!manifest) return files;
  for (const route of manifest.routes) files.add(route.file);
  for (const asset of manifest.assets) files.add(asset.file);
  return files;
}
