import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { envFilePath, getJfRoot } from "./jf-root.js";
import { assertSafeEnvValue } from "./env-file.js";
import { resetJfCache, wipeCacheStorage } from "./jf-cache.js";

const require = createRequire(import.meta.url);

export interface InstallConfig {
  dbDriver:    "postgres" | "mysql" | "mariadb";
  dbHost:      string;
  dbPort:      number;
  dbName:      string;
  dbUser:      string;
  dbPassword:  string;
  // Pre-built `driver://user:pass@host:port/name` connection string (already
  // percent-encoded by the caller) — @justflows/core's loadConfig() reads this
  // as DATABASE_URL and throws without it, so jf-cache/plugin-runtime/etc.
  // silently degrade on every fresh install unless it lands in .env too.
  databaseUrl: string;
  appUrl:      string;
  appSecret:   string;
  siteId:      string;
  installedAt: string;
  version:     string;
}

/** .env body written by the install wizard. Cache starts fully off. */
export function installedEnvContents(config: InstallConfig): string {
  return [
    `# Justflows — generated by install wizard. Keep private (chmod 600 .env).`,
    ``,
    `STATE=INSTALLED`,
    ``,
    `NODE_ENV=production`,
    `APP_URL=${config.appUrl}`,
    `APP_SECRET=${config.appSecret}`,
    ``,
    `DB_DRIVER=${config.dbDriver}`,
    `DATABASE_DRIVER=${config.dbDriver}`,
    `DB_HOST=${config.dbHost}`,
    `DB_PORT=${config.dbPort}`,
    `DB_NAME=${config.dbName}`,
    `DB_USER=${config.dbUser}`,
    `DB_PASSWORD=${config.dbPassword}`,
    // Discrete DB_* vars above drive the app's own db.ts client; this
    // composed form is what @justflows/core's loadConfig() reads. Without it,
    // loadConfig() throws on every call and plugin-runtime silently refuses
    // to start (see ensurePluginRuntime()'s catch block).
    `DATABASE_URL=${config.databaseUrl}`,
    ``,
    `# Storage`,
    `STORAGE_DRIVER=local`,
    `STORAGE_LOCAL_PATH=./uploads`,
    ``,
    `# Ports & logging`,
    `PORT=3000`,
    `LOG_LEVEL=info`,
    `JF_DEBUG=false`,
    ``,
    `# Cache (jf-cache) — off until the owner enables it in Admin → Tools.`,
    `CACHE_ENABLED=0`,
    `CACHE_DRIVER=filesystem`,
    `CACHE_TTL_SECONDS=300`,
    `CACHE_DIR=./.cache`,
    `CACHE_REVALIDATE_ENABLED=0`,
    `CACHE_REVALIDATE_OBJECTS=pages,content,menus,theme,cssProviders,site`,
    ``,
    `# Performance`,
    `JF_GZIP_ENABLED=0`,
    `JF_GZIP_LEVEL=6`,
    `JF_GZIP_MIN_BYTES=1024`,
    `JF_BROWSER_CACHE_ENABLED=0`,
    `JF_BROWSER_CACHE_HTML_MAX_AGE=60`,
    `JF_BROWSER_CACHE_STATIC_MAX_AGE=86400`,
    `JF_BROWSER_CACHE_SWR=300`,
  ].join("\n");
}

function applyInstalledEnvToProcess(config: InstallConfig): void {
  process.env.STATE        = "INSTALLED";
  process.env.APP_URL      = config.appUrl;
  process.env.APP_SECRET   = config.appSecret;
  process.env.DB_DRIVER    = config.dbDriver;
  process.env.DATABASE_DRIVER = config.dbDriver;
  process.env.DB_HOST      = config.dbHost;
  process.env.DB_PORT      = String(config.dbPort);
  process.env.DB_NAME      = config.dbName;
  process.env.DB_USER      = config.dbUser;
  process.env.DB_PASSWORD  = config.dbPassword;
  process.env.DATABASE_URL = config.databaseUrl;
  process.env.STORAGE_DRIVER = "local";
  process.env.STORAGE_LOCAL_PATH = "./uploads";
  process.env.PORT         = "3000";
  process.env.LOG_LEVEL    = "info";
  process.env.CACHE_ENABLED = "0";
  process.env.CACHE_DRIVER = "filesystem";
  process.env.CACHE_TTL_SECONDS = "300";
  process.env.CACHE_DIR    = "./.cache";
  process.env.CACHE_REVALIDATE_ENABLED = "0";
  process.env.CACHE_REVALIDATE_OBJECTS = "pages,content,menus,theme,cssProviders,site";
  process.env.JF_GZIP_ENABLED = "0";
  process.env.JF_GZIP_LEVEL = "6";
  process.env.JF_GZIP_MIN_BYTES = "1024";
  process.env.JF_BROWSER_CACHE_ENABLED = "0";
  process.env.JF_BROWSER_CACHE_HTML_MAX_AGE = "60";
  process.env.JF_BROWSER_CACHE_STATIC_MAX_AGE = "86400";
  process.env.JF_BROWSER_CACHE_SWR = "300";
}

/**
 * Write .env with STATE=INSTALLED and all credentials.
 * chmod 600 — owner read/write only.
 * Next.js loads .env at startup so process.env.STATE is available immediately
 * on the next request without a server restart (Next.js re-reads .env per request
 * in production via its built-in env handling for dynamic routes).
 */
export async function markInstalled(config: InstallConfig): Promise<void> {
  // Every one of these lands in .env verbatim. appUrl is written before the
  // generated APP_SECRET and dotenv keeps first-wins, so a newline here would
  // let the caller pick the session signing key.
  assertSafeEnvValue("APP_URL", config.appUrl);
  assertSafeEnvValue("APP_SECRET", config.appSecret);
  assertSafeEnvValue("DB_HOST", config.dbHost);
  assertSafeEnvValue("DB_NAME", config.dbName);
  assertSafeEnvValue("DB_USER", config.dbUser);
  assertSafeEnvValue("DB_PASSWORD", config.dbPassword);
  assertSafeEnvValue("DATABASE_URL", config.databaseUrl);

  const lines = installedEnvContents(config);

  await fs.writeFile(envFilePath(), lines, { encoding: "utf-8", mode: 0o600 });
  await fs.chmod(envFilePath(), 0o600).catch(() => undefined);

  // Apply immediately to the running process so the layout check works
  // on the very next request without needing a restart.
  applyInstalledEnvToProcess(config);
  resetJfCache();
  await wipeCacheStorage();

  try {
    const gate = require(path.join(getJfRoot(), "scripts/bootstrap-gate.cjs")) as {
      removeBootstrapIndex: (root: string) => boolean;
    };
    gate.removeBootstrapIndex(getJfRoot());
  } catch {
    // Bootstrap page is only present on unzipped releases.
  }

  // The token is spent. Leaving it behind would put a stale secret in a folder
  // the site owner has no reason to revisit.
  const { clearInstallToken } = await import("./install-token.js");
  clearInstallToken(getJfRoot());

  // Same reasoning for the bootstrap transcript: it records absolute paths and
  // the whole dependency tree, and it outlived the install by months because
  // nothing ever removed it.
  for (const name of ["bootstrap.log", "bootstrap-status.json"]) {
    await fs.rm(path.join(getJfRoot(), "tmp", name), { force: true }).catch(() => undefined);
  }
}
