import fs from "node:fs/promises";
import { envFilePath } from "./jf-root.js";

export interface InstallConfig {
  dbDriver:    "postgres" | "mysql" | "mariadb";
  dbHost:      string;
  dbPort:      number;
  dbName:      string;
  dbUser:      string;
  dbPassword:  string;
  appUrl:      string;
  appSecret:   string;
  siteId:      string;
  installedAt: string;
  version:     string;
}

/**
 * Write .env with STATE=INSTALLED and all credentials.
 * chmod 600 — owner read/write only.
 * Next.js loads .env at startup so process.env.STATE is available immediately
 * on the next request without a server restart (Next.js re-reads .env per request
 * in production via its built-in env handling for dynamic routes).
 */
export async function markInstalled(config: InstallConfig): Promise<void> {
  const lines = [
    `# Justflows — generated by install wizard. Keep private (chmod 600 .env).`,
    ``,
    `STATE=INSTALLED`,
    ``,
    `NODE_ENV=production`,
    `APP_URL=${config.appUrl}`,
    `APP_SECRET=${config.appSecret}`,
    ``,
    `DB_DRIVER=${config.dbDriver}`,
    `DB_HOST=${config.dbHost}`,
    `DB_PORT=${config.dbPort}`,
    `DB_NAME=${config.dbName}`,
    `DB_USER=${config.dbUser}`,
    `DB_PASSWORD=${config.dbPassword}`,
    ``,
    `# Cache (jf-cache)`,
    `CACHE_ENABLED=1`,
    `CACHE_DRIVER=filesystem`,
    `CACHE_TTL_SECONDS=300`,
    `CACHE_DIR=./.cache`,
    `CACHE_REVALIDATE_ENABLED=1`,
    `CACHE_REVALIDATE_OBJECTS=pages,content,menus,theme,cssProviders,site`,
    ``,
    `# Performance`,
    `JF_GZIP_ENABLED=1`,
    `JF_GZIP_LEVEL=6`,
    `JF_GZIP_MIN_BYTES=1024`,
    `JF_BROWSER_CACHE_ENABLED=1`,
    `JF_BROWSER_CACHE_HTML_MAX_AGE=60`,
    `JF_BROWSER_CACHE_STATIC_MAX_AGE=86400`,
    `JF_BROWSER_CACHE_SWR=300`,
  ].join("\n");

  await fs.writeFile(envFilePath(), lines, { encoding: "utf-8", mode: 0o600 });

  // Apply immediately to the running process so the layout check works
  // on the very next request without needing a restart.
  process.env.STATE        = "INSTALLED";
  process.env.APP_URL      = config.appUrl;
  process.env.APP_SECRET   = config.appSecret;
  process.env.DB_DRIVER    = config.dbDriver;
  process.env.DB_HOST      = config.dbHost;
  process.env.DB_PORT      = String(config.dbPort);
  process.env.DB_NAME      = config.dbName;
  process.env.DB_USER      = config.dbUser;
  process.env.DB_PASSWORD  = config.dbPassword;
  process.env.CACHE_ENABLED = "1";
  process.env.CACHE_DRIVER = "filesystem";
  process.env.CACHE_TTL_SECONDS = "300";
  process.env.CACHE_DIR    = "./.cache";
  process.env.CACHE_REVALIDATE_ENABLED = "1";
  process.env.CACHE_REVALIDATE_OBJECTS = "pages,content,menus,theme,cssProviders,site";
  process.env.JF_GZIP_ENABLED = "1";
  process.env.JF_GZIP_LEVEL = "6";
  process.env.JF_GZIP_MIN_BYTES = "1024";
  process.env.JF_BROWSER_CACHE_ENABLED = "1";
  process.env.JF_BROWSER_CACHE_HTML_MAX_AGE = "60";
  process.env.JF_BROWSER_CACHE_STATIC_MAX_AGE = "86400";
  process.env.JF_BROWSER_CACHE_SWR = "300";
}
