// SPDX-License-Identifier: MIT

import fs from "node:fs/promises";
import path from "node:path";

/**
 * Shared prefix for the first line of any Justflows-generated web-server config
 * file (`_headers`, the static-export `.htaccess` / `_nginx.conf`, the site-root
 * `.htaccess`). While the first line still starts with this, the generator that
 * owns the file rewrites it on the next run; change or remove that line — or
 * delete the file — to keep hand edits.
 */
export const MANAGED_SENTINEL = "# Generated by Justflows";

/**
 * Write a managed config file only when it is absent or still carries the
 * sentinel first line, so a hand-edited file is never clobbered. Returns what it
 * did so the caller can log a skip.
 */
export async function writeManagedFile(
  dir: string,
  filename: string,
  body: string,
): Promise<"written" | "unchanged" | "kept-custom"> {
  const file = path.join(dir, filename);
  let existing: string | null = null;
  try {
    existing = await fs.readFile(file, "utf8");
  } catch {
    existing = null;
  }
  if (existing !== null) {
    const firstLine = existing.split("\n", 1)[0]?.trim() ?? "";
    if (!firstLine.startsWith(MANAGED_SENTINEL)) return "kept-custom";
    if (existing === body) return "unchanged";
  }
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(file, body, "utf8");
  return "written";
}
